### ISSUE TITLE
Bundle kubectl?

### ISSUE THREAD

**Issue by rosskukulinski** [rosskukulinski/k8s-scripts#6]
Should k8s-scripts include kubectl binaries or install via npm post-install step?

**Comment by jmound** [comment]
I think the install via wget is fine, but "1.2.0" should probably not be [hard coded](https://github.com/rosskukulinski/k8s-scripts/blob/master/bin/ensure-kubectl.sh#L55).

**Comment by rosskukulinski** [comment]
kubeclt version no longer hard-coded
